### ISSUE TITLE
Schema representation is not updated when source file is updated

### ISSUE THREAD

**Issue by StefanD986** [lnoor/sphinx-jsonschema#2]
I load my JSON Schema  from a local source file with 
`.. jsonschema:: source/SomeJSONSchemaFile.json`

When I change the content `SomeJSONSchemaFile.json` and then rebuild the documentation, the changes are note represented in the output. Onlyh after a clean build the documentation shows the changes.

**Comment by lnoor** [comment]
Sphinx doesn't know about the dependency on the json file.
Frankly, I wouldn't know if that dependency can be defined in Sphinx.

What you *can* do is declare the dependency in your Makefile (if you use the make utility).
Here you can state that the .html depends on the .rst file which in turn depends on the .json file.
Now if any of the sources change the target will be rebuilt.

It does require a handcrafted Makefile since the one generated by Sphinx isn't readily adapted.

**Comment by lnoor** [comment]
no follow up

**Comment by StefanD986** [comment]
Sorry for not following up on yout comment yet, the weekend came inbetween.

Since it seems to be a limitation of Sphinx I guess it is okay to close the issue.

**Comment by lnoor** [comment]
Ah sorry, I meant I won't follow up.
Didn't mean to address you in any way.
I apologize!
