### ISSUE TITLE
Follow $ref to include files

### ISSUE THREAD

**Issue by wkerzendorf** [lnoor/sphinx-jsonschema#22]
This is a great little package!! Thanks for sharing it ... now come the complaints :wink: 

We store our schemas (to vet configuration files) here https://github.com/tardis-sn/tardis/tree/master/tardis/io/schemas and use the `base.yml` that includes all other files. 

If I specify `base.yml` it does not seem to include the other files. 

I think it also doesn't deal well with `anyOf` as @ftsamis told me.

**Comment by lnoor** [comment]
Thanks for the compliment (and the issue report).
You're a bit vague at what goes wrong but looking at the schemas I have a hunch I'd like you to try out.

I think the problem is that the references cannot be resolved as they are relative to somewhere and the 'somewhere' is not specified.

So can you include a line:
```id: https://github.com/tardis-sn/tardis/tree/master/tardis/io/schemas/base.yml```
on the second line after $schema?
Or use full references instead of relative ones; i.e.
replace ```$ref: supernova.yml``` with ```$ref: https://github.com/tardis-sn/tardis/tree/master/tardis/io/schemas/supernova.yml```?

Either should work and resolve your problem. Personally I prefer to include the "id" key.
Let me know if this works for you.

**Comment by wkerzendorf** [comment]
@lnoor (sorry for the long delay in answering) Doesn't seem to work : https://github.com/wkerzendorf/tardis/blob/doc/schema/docs/configuration/config_validator.rst

see the documentation at https://tardis.readthedocs.io/en/docs-prepare_release/configuration/config_validator.html

**Comment by lnoor** [comment]
As far as I can tell it does work.
You need to understand that the $ref is **not** resolved **inline**.
Rather a link (rst ref) is created referencing the $ref target.

Replace
```
Our Schema
^^^^^^^^^^


.. jsonschema:: base.yml
```

by


```
Our Schema
^^^^^^^^^^


.. jsonschema:: base.yml

.. jsonschema:: https://github.com/tardis-sn/tardis/tree/master/tardis/io/schemas/supernova.yml
```

Only now is supernova.yml pulled in and displayed.
However when I try to download supernova.yml I get to see a HTML document not a YAML document.

I suggest you collect all related files locally and first try to get it working that way (with file references).
Also you will need to include a $$target entry in the supernova.yml file. The contents of $$target should match exactly with the $ref value.

**Comment by wkerzendorf** [comment]
@lnoor It can't resolve it inline - that would be quite important for us. Is there a way to add this? Can I help?

**Comment by lnoor** [comment]
It was not designed to do that.
Especially with larger schemas that just doesn't display nicely.
The indentation levels will become to deep.
See [Zipcode reply](http://api.nextpertise.nl/documentation/broadband/zipcode.html#zipcode-reply-v1)  for an example.

To see for yourself just replace the $ref with the contents of supernova.
If you still want to inline the references then by all means do; just make sure that it is an optional feature (perhaps using a flag ```:inline_references:``` or something similar).

In that case you need to modify wide_format.py line 74 to either do what it does now or to recursively call _dispatch() with the contents of the file referenced by the $ref. You may want to refactor the ```__init__.py``` function ```_load_external()``` to do this.

**Comment by wkerzendorf** [comment]
@lnoor thank you. I guess you are right (it would be great to have little toggle trees where you can open and close sections).

Here is the current final product spelling things out. Definitions also don't seem to work, but for now things are fine. 

Thanks for this great piece of software!!

**Comment by lnoor** [comment]
Looks very good, I should take a look at your css!
But given that supernova.yml is not a clickable link means that something isn't right yet.
Willing to make the most of it?

If so make these changes:
prepend
```
title: Supernova
$$target: supernova.yml
```
to your ```schemas/supernova.yml```.

To make it easier to experiment you may want to replace the symlinks with copies of these files.
I think you'll like the result.

The value of $$target should match exactly with $ref and the referenced document should have a title for the link to appear.

I'm not sure why your definitions aren't working.
I need to look into that.

**Comment by wkerzendorf** [comment]
@lnoor on it - will show you what happens. I want things to be symlinks to ensure that if people update the schemas it shows up in the documentation

**Comment by wkerzendorf** [comment]
@lnoor here it is:https://tardis.readthedocs.io/en/docs-prepare_release/configuration/configuration.html

**Comment by wkerzendorf** [comment]
@lnoor - let me know how we can help with the definition inclusion

**Comment by wkerzendorf** [comment]
ah - and the jsonschema-sphinx html does not do text wrapping

**Comment by lnoor** [comment]
Can't help with the text wrapping (I think).
I basically create a (nested) table like you would in rst from the schema and feed that to docutils; the library that drives sphinx.
If a manually created table exhibits the same problem you should contact the docutils people.
Otherwise I need to take another look at sphinx-jsonschema.

And yes Wolfgang; I can really use some help with the definitions thing.
Wonderful that you're willing to help out.
May I come back to you in the weekend?

**Comment by lnoor** [comment]
@wkerzendorf I never used definitions since I find them of limited value for large schemas.
However it would be nice if the are implemented properly.
Basically I can think of two ways to implement it:
- expand the ref inline
- display the keys under definitions as distinct schemas and use the existing ref linking.

I would prefer the second method because it reduces the depth of the table being created.
That in turn makes it easier to properly display the result in formats other than html; like epub or pdf.
(It probably is also less work to implement).

What are your views on this and are you interested implementing it?

**Comment by wkerzendorf** [comment]
@lnoor probably second one is a better option. I'll have a look tomorrow
