### ISSUE TITLE
Add support for "up one level" relative paths

### ISSUE THREAD

**Issue by immber** [lnoor/sphinx-jsonschema#25]
Relative paths don't support using "up one level" `../` syntax 

In https://github.com/lnoor/sphinx-jsonschema/blob/master/sphinx-jsonschema/__init__.py#L64

```if not os.path.isabs(file_or_url):
                # file relative to the path of the current rst file
                dname = os.path.dirname(self.statemachine.input_lines.source(0))
                file_or_url = os.path.join(dname, file_or_url)
```

it would be really nice if relatives paths were actually supported. I'm building docs from `/docs` folder in a repo and want to ref a path to a json in the same repo outside the current documentation directory.

**Comment by lnoor** [comment]
Thanks for reporting.
I believe it does work so I need more information about what you are trying to do.

My own directory structure looks like (using 2 files as examples):

- base/documentation/broadband/basic/zipcode.rst and
- base/documentation/fieldtypes.rst

refering to

- base/schemas/broadband/basic/zipcode_request_v1.json and
- base/schemas/shared/types_v1.json.

The result can be viewed here: 

- http://api.nextpertise.nl/documentation/broadband/basic/zipcode.html and
- http://api.nextpertise.nl/documentation/fieldtypes.html

The base/documentation directory is from where Sphinx is run containing `conf.py`, `Makefile` etc.

In the zipcode.rst file I refer to the schema using the statement:
`.. jsonschema:: ../../../schemas/broadband/basic/zipcode_request_v1.json`

And in the fieldtypes.rst file I refer to the schemas using statements like:
`.. jsonschema:: ../schemas/shared/types_v1.json#/location`

If this is similar to what you want I guess you've made a mistake somewhere.
Otherwise please share in more detail what you want to do.
Include a minimal example if you have to.

**Comment by lnoor** [comment]
Hi @immber Did the previous comment help you or are you still having problems?
