### ISSUE TITLE
Implement $id instead of $$target

### ISSUE THREAD

**Issue by paulineleon** [lnoor/sphinx-jsonschema#32]
The non standard **$$target** should be replaced by a proper implementation of **$id** and **$ref**. In particular, using paths including **/** in a **$ref** will lead to inconsistent interpretation by **$$target** (expect **$id** to be the full path) and **$id** (expect **$id** to be the basename of **$ref**)

See [section 8.2.4.1.  Direct References with "$ref"](https://datatracker.ietf.org/doc/draft-handrews-json-schema/?include_text=1)

**Comment by lnoor** [comment]
You are welcome to provide a pull request.
Do make sure that your version will allow me to do all that the current version does.

**Comment by paulineleon** [comment]
Please reopen this bug report until it is fixed.

**Comment by lnoor** [comment]
Very well but please explain what the bug is.
The standard explicitly allows non standard elements.
As implementations should ignore unknown elements it does not affect validation.
It solves a very real problem that I couldn't properly solve using just `id`.
So what is the problem you are facing?

**Comment by paulineleon** [comment]
Thanks. The problem is that if you have a $ref with **/** in them, you can either run a validator (https://github.com/epoberezkin/ajv for instance) or sphinx-jsonschema. But not both because their intepretation of $id and $$target are mutually exclusive.

**Comment by lnoor** [comment]
I'm afraid it is still unclear to me.
`id` (not `$id`, sphinx-jsonschema is basically still **draft 4**) is not interpreted, only printed by sphinx-jsonschema. `$id` is completely unknown and ignored.
`$$target` should be ignored by a conforming validator.
So I do not see why they are mutually exclusive.

Looking at your validator I wonder if you are adding `$$target` as a new keyword to the validator.
That would result in the validator assigning meaning to `$$target`.
In that case I suggest to:

- not do that or otherwise
- accept any parameter (string or array of strings) for `$$target` and always succeed (so basically ignoring it during validation).

**Comment by paulineleon** [comment]
Hum, indeed. It looks like the root of the confusion is that I'm using validation against draft 07, because my schema use draft 07.

**Comment by paulineleon** [comment]
https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.2 has $id which presumably did not exist back when draft 4 was published ?

**Comment by paulineleon** [comment]
I'll experiment a little more and report back my findings.

**Comment by lnoor** [comment]
`id` or `$id` shouldn't make much of a difference.
sphinx-jsonschema is not a validator and is thus quite forgiving when it finds something unknown and treats both of them more or less similar.
In draft 4, `id` was used. It was later changed to `$id`.

I keep this issue open and am curious to learn your findings.

**Comment by paulineleon** [comment]
Thanks for your patience. After trying to create a reproducer (and with a better understanding of what $$target should contain) it turns out to work as expected.

**Comment by lnoor** [comment]
Hang on, not that fast :)
Clearly the documentation is lacking.
Can you offer a suggestion on how to improve it?

**Comment by paulineleon** [comment]
:-) I'm not sure but here is how I got lost.

* I thought **$ref** was a URL that the validator would fetch and it took me a while to figure out it was just referencing an **$id** that had no relation to the actual location of the file. It is entirely unrelated to sphinx-jsonchema but contributed to me being confused.
* When running sphinx with sphinx-jsonschema for the first time I got confused by the error message
   > sphinx.errors.SphinxWarning: <unknown>:1:undefined label: civ.json (if the link has no caption the label must precede a section header)
   and tried to move the "$id" around in the schema because I had no clue what "label" meant in this context, nor what a section was about (now I do: it's not in the schema)
* I got further confused by the fact that civ.json was lowercase where my $id was Civ.json but again, not a message about the schema
* Then I tried using the full path names of all files for $ref and $id but it did not help
* Then I read the documentation once more (too quickly again) and figured $$target was missing. I added it and ... voila, it passed sphinx!
* Then I ran the validator again and it failed miserably because it used the basename of the $ref to match the $id

I'm not proud of me bumping into walls like a headless chicken, but you asked for the full story and here it is.

Thanks again for your patience.

**Comment by ankostis** [comment]
(if you don't mind some nose-poking)
Thank you for sharing your work with the generalpublic.
i'm still baffled, ...why isn't `$id` (from draft07) as good property as `$$target`?

- Why couldn't you use `$id` (which is unrelated to draft04 but still allowe)?
 I mean, what was the problem that you couldn't solve with `$id`, and needed to invent `$$target`, which inverses the lnk (so the linked document must know all its references, which requires extra attention).
- Related question, why should each target-document needs a separate directive, instead of resolving `$ref` from the "current" document, or the document with a matching `$id` part?

**Comment by lnoor** [comment]
Okay, as to the **why**: ( shouldn't confessions be private? ;-) 

To understand the choices I made you need to understand what problem I wanted to solve;
besides the obvious: reuse schema for documentation as well as validation.

I had a large number of schemas all referring to a shared schema defining a whole bunch of common types.
Due to the size and number of schemas I wanted to control where each schema (segment) is included in the documentation.
The `$ref`'s were most often using relative paths instead of absolute ones.

One solution is to canonize the `$ref`'s and always use absolute paths with proper escaping.
Which proved somewhat tricky to implement correctly.
And I needed something ASAP, I was *not* creating a nice piece of software, just solving my problem.

`$$target` allowed my to sidestep the issue because it allowed me to provide exactly the same string used in the `$ref`.
As there were multiple relative paths used, `$$target` evolved into an array.

Beautiful? No!
Effective? Yes.

As for the **related** question, I'm not quite sure what you're asking.
I am aware of another json schema extension for sphinx which basically incorporates the entire schema into the documentation resolving references on-the-go but that is not what I wanted.

I wanted to be able to discuss each schema part where necessary and provide context by allowing schema parts to refer to each other replacing the `$ref`'s with proper HTML links.
In my documentation I included each target-document explicitly, so I could show a couple of schema fragments
discuss those, then show some more fragments.

Each fragment was explicitly included using its own `.. json-schema::` entry using json path to select just that one fragment.
Therefore each fragment needed to have its own `$$target` entry.

You may not like it but that is just how it is.
The nice thing is there is room for improvement and you are most welcome to it.
Let's just discuss solutions before you implement anything so a PR will be accepted.
