### ISSUE TITLE
Improve items rendering

### ISSUE THREAD

**Issue by nijel** [lnoor/sphinx-jsonschema#49]
When there are items used in the schema, it gets rendered as table with empty bullet:

![image](https://user-images.githubusercontent.com/212189/93881809-aedf5580-fcdf-11ea-82e4-7daadaa8d59b.png)

This looks like some content is missing, but it is actually not missing...

Related schema is https://github.com/WeblateOrg/weblate_schemas/blob/master/weblate_schemas/schemas/weblate-memory.schema.json

Originally reported by @baffclan in https://github.com/WeblateOrg/weblate/issues/4570

**Comment by lnoor** [comment]
The outermost bullet directly under the word 'items' is by design.
I need to deliniate the individual items making up the array.
Alternatives would be to use a numeric index or something similar.

Do you have a suggestion how to render an array of (possibly deeply) nested objects?

**Comment by nijel** [comment]
There is always just one type under items, right? In case it's true, I'd prefer to put the items directly under items table row:

![image](https://user-images.githubusercontent.com/212189/94661032-ced9cf00-0306-11eb-8af7-879c96df5b47.png)

Making the "items" td rowspan instead of the td with empty list. That eliminates the blank table row and not needed empty list cell.

**Comment by lnoor** [comment]
Ah, but unfortunately that is not true.
The [latest standard](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.1) says 
that ``items`` can contain either a schema or an array of schemas.
Which has been the case at least since draft-4.

I've implemented this by always representing it as an array.
That is definitely inexact!
I will look into this on how to make the array representation dependent on the presence of an array in the source schema.
